import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ThemeProvider } from "next-themes";
import { CartProvider } from "@/utils/contextReducer";
import { AuthProvider } from "@/utils/authContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body>
      <ThemeProvider attribute="class">
      <AuthProvider>
        <CartProvider>
          <ToastContainer />
        <Navbar/>
        {children}
        <Footer/>
       
        </CartProvider>
        </AuthProvider>
        </ThemeProvider>
        
        </body>
    </html>
  );
}
